### ISSUE TITLE
Assertion on update at relpath.is_relative()

### ISSUE THREAD

**Issue by CraZySacX** [rust-lang-nursery/multirust-rs#116]
After building the latest from source I'm getting the following:

```
multirust: /usr/lib/libcrypto.so.1.0.0: no version information available (required by multirust)
multirust: /usr/lib/libssl.so.1.0.0: no version information available (required by multirust)
info: updating existing install for 'stable'
info: downloading toolchain manifest
info: downloading component 'rust'
101.15 MiB / 101.15 MiB (100.00%) 2.02 MiB/s ETA: 0s                
info: installing component 'rust'
thread '<main>' panicked at 'assertion failed: relpath.is_relative()', src/multirust-dist/src/component/transaction.rs:95
stack backtrace:
   1:     0x565410603b00 - sys::backtrace::tracing::imp::write::h3bbb320d569781f92cv
   2:     0x56541060b91f - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44520
   3:     0x56541060b598 - panicking::default_handler::hf1209fec3f963ae7H0z
   4:     0x5654105f1dec - sys_common::unwind::begin_unwind_inner::h2ff9ae045f111c6dg2t
   5:     0x5654104ec64f - sys_common::unwind::begin_unwind::h7212872284514612386
   6:     0x565410509efb - component::transaction::Transaction<'a>::remove_file::h9544c8442a783c110kc
   7:     0x565410519fe5 - component::components::Component::uninstall::h9a6107b57ed759ecapd
   8:     0x5654105010a2 - manifestation::Manifestation::update_v1::h0ece6bad2a988f941Ud
   9:     0x5654104f368a - dist::update_from_dist::h4d163cc7775cd55654a
  10:     0x5654104879b3 - toolchain::Toolchain<'a>::install::h714c92d06aaa2740jgb
  11:     0x565410489564 - toolchain::Toolchain<'a>::install_from_dist::h2fea8116ac6d182c8kb
  12:     0x5654104620cb - multirust_mode::main::hf3ce55e6947784e16Oa
  13:     0x56541045994b - main::h83365d9fe8e27bedmIc
  14:     0x56541060b1f4 - sys_common::unwind::try::try_fn::h12478214143095739015
  15:     0x565410602efb - __rust_try
  16:     0x56541060ac8b - rt::lang_start::h4f110050dd8fc253NSz
  17:     0x7faa0ecb970f - __libc_start_main
  18:     0x5654104590d8 - <unknown>
  19:                0x0 - <unknown>
info: rolling back changes
```

I've tried various combinations of toolchains, but they all fail the same way.

**Comment by CraZySacX** [comment]
I completely removed my ```.multirust``` directory and let it rebuild and this issue did not happen again.    Closing.

**Comment by ghost** [comment]
<details><summary>Just hit this issue even with the latest rustup.rs master: 174e272b31e277bf83f1947b5317ccb1541af07a</summary>

```rust
user@z575 2019/03/30 20:28:14 -bash5.0.2 t:0 j:0 d:3 pp:854 p:26918 ut16539
!19047 1 0  5.0.0-g1c163f4c7b3f #13 SMP PREEMPT Tue Mar 26 00:37:32 CET 2019
/home/user 
$ RUST_BACKTRACE=1 rustup update
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
glibc64:../sysdeps/posix/getaddrinfo.c:2212/getaddrinfo: rustup[27020](full:'rustup') for user user(1000(eff:user(1000))) 1of2 attempting to resolve (requested)hostname:
static.rust-lang.org
glibc64:../sysdeps/posix/getaddrinfo.c:2212/getaddrinfo: rustup[27020](full:'rustup') for user user(1000(eff:user(1000))) 2of2 successfully resolved requested hostname('static.rust-lang.org') which was not transformed('static.rust-lang.org') as follows:
143.204.214.53 static.rust-lang.org
info: latest update on 2019-03-30, rust version 1.35.0-nightly (e782d790f 2019-03-29)
info: downloading component 'rustc'
info: downloading component 'rust-std'
info: downloading component 'cargo'
info: downloading component 'rust-docs'
info: removing component 'rustc'
info: removing component 'rust-std'
thread 'main' panicked at 'assertion failed: relpath.is_relative()', src/rustup-dist/src/component/transaction.rs:95:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:70
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   2: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:215
             at src/libstd/panicking.rs:478
   3: std::panicking::begin_panic
   4: rustup_dist::component::transaction::Transaction::remove_file
   5: rustup_dist::component::components::Component::uninstall
   6: rustup_dist::manifestation::Manifestation::update
   7: rustup_dist::dist::update_from_dist_
   8: rustup::toolchain::Toolchain::install
   9: rustup::toolchain::Toolchain::install_from_dist
  10: <core::iter::Map<I, F> as core::iter::iterator::Iterator>::next
  11: rustup_init::rustup_mode::update
  12: rustup_init::rustup_mode::main
  13: rustup_init::run_rustup
  14: rustup_init::main
  15: std::rt::lang_start::{{closure}}
  16: main
  17: __libc_start_main
             at ../csu/libc-start.c:308
  18: <unknown>
info: rolling back changes
```
</details>

The relative path, which is actually absolute here, is: `/home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libvoid-097c0b336d8900d0.rlib`

That file seems to be there from my last successful attempt at installing a locally-compiled rustc, with the config.toml `[install]` prefix is `prefix = "/home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu"`
(that rustc actually fails to compile firefox-hg but that's another issue, so I wanted to try with rustup nightly instead, hence why I hit this issue)

In order to see the above path the following patch was applied:

```diff
diff --git a/src/dist/component/transaction.rs b/src/dist/component/transaction.rs
index d790da18..f6d2b55a 100644
--- a/src/dist/component/transaction.rs
+++ b/src/dist/component/transaction.rs
@@ -92,7 +92,7 @@ impl<'a> Transaction<'a> {
 
     /// Remove a file from a relative path to the install prefix.
     pub fn remove_file(&mut self, component: &str, relpath: PathBuf) -> Result<()> {
-        assert!(relpath.is_relative());
+        assert!(relpath.is_relative(), "Expected relative path but got an absolute one: '{:?}'",relpath);
         let item = ChangedItem::remove_file(&self.prefix, component, relpath, &self.temp_cfg)?;
         self.change(item);
         Ok(())
```

Output with patch (and recompiled with `cargo install --debug --verbose --force --path .`):

```rust
user@z575 2019/03/30 21:13:26 -bash5.0.2 t:1 j:0 d:3 pp:854 p:23104 ut19251
!19116 7 3  5.0.0-g1c163f4c7b3f #13 SMP PREEMPT Tue Mar 26 00:37:32 CET 2019
/home/user/build/2nonpkgs/rust.stuff/rustup.rs/rustup.rs 
$ time RUST_BACKTRACE=1 rustup update
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
glibc64:../sysdeps/posix/getaddrinfo.c:2212/getaddrinfo: rustup[31694](full:'rustup') for user user(1000(eff:user(1000))) 1of2 attempting to resolve (requested)hostname:
static.rust-lang.org
glibc64:../sysdeps/posix/getaddrinfo.c:2212/getaddrinfo: rustup[31694](full:'rustup') for user user(1000(eff:user(1000))) 2of2 successfully resolved requested hostname('static.rust-lang.org') which was not transformed('static.rust-lang.org') as follows:
13.32.28.10 static.rust-lang.org
info: latest update on 2019-03-30, rust version 1.35.0-nightly (e782d790f 2019-03-29)
info: downloading component 'rustc'
info: downloading component 'rust-std'
info: downloading component 'cargo'
info: downloading component 'rust-docs'
info: removing component 'rustc'
info: removing component 'rust-std'
thread 'main' panicked at 'Expected relative path but got an absolute one: '"/home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libvoid-097c0b336d8900d0.rlib"'', /home/user/build/2nonpkgs/rust.stuff/rustup.rs/rustup.rs/src/dist/component/transaction.rs:95:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:71
             at src/libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:336
   7: rustup::dist::component::transaction::Transaction::remove_file
             at ./src/dist/component/transaction.rs:95
   8: rustup::dist::component::components::Component::uninstall
             at ./src/dist/component/components.rs:297
   9: rustup::dist::manifestation::Manifestation::uninstall_component
             at ./src/dist/manifestation.rs:300
  10: rustup::dist::manifestation::Manifestation::update
             at ./src/dist/manifestation.rs:188
  11: rustup::dist::dist::update_from_dist_
             at ./src/dist/dist.rs:553
  12: rustup::dist::dist::update_from_dist
             at ./src/dist/dist.rs:507
  13: rustup::install::InstallMethod::run
             at ./src/install.rs:55
  14: rustup::toolchain::Toolchain::install
             at ./src/toolchain.rs:110
  15: rustup::toolchain::Toolchain::install_from_dist
             at ./src/toolchain.rs:164
  16: rustup::config::Cfg::update_all_channels::{{closure}}::{{closure}}
             at ./src/config.rs:387
  17: core::result::Result<T,E>::and_then
             at /home/user/build/2nonpkgs/rust.stuff/rust/rust/src/libcore/result.rs:637
  18: rustup::config::Cfg::update_all_channels::{{closure}}
             at ./src/config.rs:386
  19: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at /home/user/build/2nonpkgs/rust.stuff/rust/rust/src/libcore/ops/function.rs:279
  20: core::option::Option<T>::map
             at /home/user/build/2nonpkgs/rust.stuff/rust/rust/src/libcore/option.rs:414
  21: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /home/user/build/2nonpkgs/rust.stuff/rust/rust/src/libcore/iter/adapters/mod.rs:568
  22: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
             at /home/user/build/2nonpkgs/rust.stuff/rust/rust/src/liballoc/vec.rs:1809
  23: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /home/user/build/2nonpkgs/rust.stuff/rust/rust/src/liballoc/vec.rs:1721
  24: core::iter::traits::iterator::Iterator::collect
             at /home/user/build/2nonpkgs/rust.stuff/rust/rust/src/libcore/iter/traits/iterator.rs:1465
  25: rustup::config::Cfg::update_all_channels
             at ./src/config.rs:397
  26: rustup_init::common::update_all_channels
             at ./src/cli/common.rs:202
  27: rustup_init::rustup_mode::update
             at ./src/cli/rustup_mode.rs:630
  28: rustup_init::rustup_mode::main
             at ./src/cli/rustup_mode.rs:45
  29: rustup_init::run_rustup
             at ./src/cli/main.rs:65
  30: rustup_init::main
             at ./src/cli/main.rs:43
  31: std::rt::lang_start::{{closure}}
             at /home/user/build/2nonpkgs/rust.stuff/rust/rust/src/libstd/rt.rs:64
  32: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  33: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  34: std::panicking::try
             at src/libstd/panicking.rs:272
  35: std::panic::catch_unwind
             at src/libstd/panic.rs:388
  36: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  37: std::rt::lang_start
             at /home/user/build/2nonpkgs/rust.stuff/rust/rust/src/libstd/rt.rs:64
  38: main
  39: __libc_start_main
             at ../csu/libc-start.c:308
  40: _start
             at ../sysdeps/x86_64/start.S:120
info: rolling back changes

real	0m29.873s
user	0m29.650s
sys	0m0.167s
```

<details><summary>Meta</summary>

```rust
$ rustv
!! LD_LIBRARY_PATH=/home/user/build/2nonpkgs/rust.stuff/rust/rust/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib:/home/user/build/2nonpkgs/rust.stuff/rust/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib:/home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib:/home/user/build/2nonpkgs/rust.stuff/rust/rust/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib:/home/user/build/2nonpkgs/rust.stuff/rust/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib:/home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib:
!! Executing '/home/user/.cargo/bin/rustc' in pwd='/home/user' with args: '-vV'
rustc 1.35.0-dev (6c49da454 2019-03-30)
binary: rustc
commit-hash: 6c49da45441d29aadd5935dabbaa8dc09ebad33a
commit-date: 2019-03-30
host: x86_64-unknown-linux-gnu
release: 1.35.0-dev
LLVM version: 8.0
!! LD_LIBRARY_PATH=/home/user/build/2nonpkgs/rust.stuff/rust/rust/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib:/home/user/build/2nonpkgs/rust.stuff/rust/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib:/home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib:/home/user/build/2nonpkgs/rust.stuff/rust/rust/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib:/home/user/build/2nonpkgs/rust.stuff/rust/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib:/home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib:
!! Executing '/home/user/build/2nonpkgs/rust.stuff/cargo/cargo//target/release//cargo' in pwd='/home/user' with args: '-vV'
cargo 1.35.0-dev (2fc2db1e 2019-03-29)
release: 1.35.0
commit-hash: 2fc2db1e0a443d5e13f0ceb544f686e6a7e0caec
commit-date: 2019-03-29

$ cd /home/user/build/2nonpkgs/rust.stuff/rustup.rs/rustup.rs && git log|head -4
commit 174e272b31e277bf83f1947b5317ccb1541af07a
Merge: fa154f67 e81c1492
Author: Daniel Silverstone <dsilvers@digital-scurf.org>
Date:   Sat Mar 30 18:08:58 2019 +0000

```

that's right I'm back baby, er I mean Hi :) :-" \*whistle\*
</details>

**Comment by kinnison** [comment]
@howaboutsynergy Are you saying that you put something inside `~/.rustup` in a manner which wasn't under rustup's control?  If so then this is not really a bug, though it'd be nice if we reported the error rather than `panic()`ing.

If you want to locally build a toolchain for use with `rustup` then please install it to somewhere else and use `rustup toolchain link`

**Comment by ghost** [comment]
Yup.
I compiled rustc and `./x.py install` put the stuff in `/home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu`, no doubt messing up the nightly toolchain, replacing at least the `rustc` executable! The idea was to replace nightly with this new compiled master. 
So it looked like this:
```
$ rustup toolchain list
nightly-x86_64-unknown-linux-gnu (default)

$ rustup show
Default host: x86_64-unknown-linux-gnu

nightly-x86_64-unknown-linux-gnu (default)
rustc 1.35.0-dev (f69422288 2019-04-01)
```

I'll try `rustup toolchain link` instead, thank you for that!



> Are you saying that you put something inside `~/.rustup` in a manner which wasn't under rustup's control? If so then this is not really a bug, though it'd be nice if we reported the error rather than `panic()`ing.

The panic happens because a function(`remove_file`) that is always expecting a relative path argument receives an absolute path one.  
Does the fact that it's unlikely to be encountered in normal circumstances disqualifies it from being a bug?

**Comment by ghost** [comment]
> If so then this is not really a bug,

Ok, I now see why it's not really a bug and thus agree with you.

All these relative paths that are absolute only in my case(due to having `./x.py install`-ed rust in prefix=`/home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu`) are taken from the contents of files named `manifest-*` located in dir `/home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib`.

So, since I wasn't supposed to install inside that dir and my `./x.py install` created manifest files with absolute paths inside their contents (eg. lines like `file:/home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-f1c66ceae80ce6c5.rlib` instead of lines like `file:lib/rustlib/x86_64-unknown-linux-gnu/lib/libsyntax_pos-ad85b205a2b14bc9.so`), it's thus not the fault of `rustup.rs` for not being able to handle those absolute paths, and in fact I'm thankful that it caught the error when it did and didn't start removing absolute path files (eg. preventing potentially removing files from my $HOME, in a tinfoil-hat case that something else tampered with those manifest* files in order to sneakily remove non-rust-related files this way)
